import '%modules%/header/header';
import '%modules%/footer/footer';
import '%modules%/popups/popups';
import '%modules%/start-section/start-section';
import '%modules%/company-section/company-section';
import '%modules%/services-section/services-section';
import '%modules%/technology-section/technology-section';
import '%modules%/team-section/team-section';
import '%modules%/reviews-section/reviews-section';
